apiVersion: v1
kind: Service
metadata:
  name: my-nodeip-svc
spec:
  type: NodePort
  selector:
        app: ip-app
  ports:
    - name: http
      nodePort: 30002
      port: 30001
      targetPort: 80
